import Vue from 'vue'
import App from './App.vue'
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css' // Ensure you are using css-loader
import vuetify from './plugins/vuetify';

// import Vuetify, {
//   VApp,
//   VAlert,
//   VBtn,
//   VRow,
//   VAvatar,
//   VImg,
//   VCard,
//   VToolbar,
//   VToolbarTitle,
//   VContainer,
//   VList,
//   VListItem,
//   VListItemAvatar,
//   VListItemTitle,
//   VListItemSubtitle,
//   VListItemContent,
//   VListItemIcon,
//   VListItemGroup,
//   VDivider,
//   VIcon,
//   VNavigationDrawer,
//   VForm,
//   VCol,
//   VTextField,
//   VCardTitle,
//   VCardSubtitle,
//   VDialog,
//   VCardText,
//   VCardActions,
//   VBreadcrumbs,
//   VTextarea,
//   VSpacer,
//   VDataTable,
//   VProgressCircular,
//   VSnackbar,
//   VFileInput,
//   VBadge,
//   VTab,
//   VTabs,
//   VTabItem,
//   VTabsItems,
//   VSkeletonLoader,
//   VChip,
//   VSheet,
//   VSpeedDial,
//   VFooter,
//   VCarousel,
//   VCarouselItem,
//   VCombobox,
//   VSwitch,
//   VOverlay,
// } from 'vuetify/lib';

// Vue.use(Vuetify, {
//   components: {
//       VApp,
//       VAlert,
//       VBtn,
//       VRow,
//       VAvatar,
//       VImg,
//       VCard,
//       VToolbar,
//       VToolbarTitle,
//       VContainer,
//       VList,
//       VListItem,
//       VListItemAvatar,
//       VListItemTitle,
//       VListItemSubtitle,
//       VListItemContent,
//       VListItemIcon,
//       VListItemGroup,
//       VDivider,
//       VIcon,
//       VNavigationDrawer,
//       VForm,
//       VCol,
//       VTextField,
//       VCardTitle,
//       VCardSubtitle,
//       VDialog,
//       VCardText,
//       VCardActions,
//       VBreadcrumbs,
//       VTextarea,
//       VSpacer,
//       VDataTable,
//       VProgressCircular,
//       VSnackbar,
//       VFileInput,
//       VBadge,
//       VTab,
//       VTabs,
//       VTabItem,
//       VTabsItems,
//       VSkeletonLoader,
//       VChip,
//       VSheet,
//       VSpeedDial,
//       VFooter,
//       VCarousel,
//       VCarouselItem,
//       VCombobox,
//       VSwitch,
//       VOverlay,
//   }
// });


Vue.use(Vuetify)
Vue.config.productionTip = false

new Vue({
  vuetify,
  render: h => h(App)
}).$mount('#app')
